// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.asy.tests.grpc.proto.user;

public interface CreateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asy.tests.grpc.proto.user.CreateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
   * @return The type.
   */
  com.asy.tests.grpc.proto.user.UserType getType();

  /**
   * <code>.google.protobuf.Timestamp birthdate = 5;</code>
   * @return Whether the birthdate field is set.
   */
  boolean hasBirthdate();
  /**
   * <code>.google.protobuf.Timestamp birthdate = 5;</code>
   * @return The birthdate.
   */
  com.google.protobuf.Timestamp getBirthdate();
  /**
   * <code>.google.protobuf.Timestamp birthdate = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder();

  /**
   * <code>bool active = 6;</code>
   * @return The active.
   */
  boolean getActive();

  /**
   * <code>repeated string numbers = 7;</code>
   * @return A list containing the numbers.
   */
  java.util.List<java.lang.String>
      getNumbersList();
  /**
   * <code>repeated string numbers = 7;</code>
   * @return The count of numbers.
   */
  int getNumbersCount();
  /**
   * <code>repeated string numbers = 7;</code>
   * @param index The index of the element to return.
   * @return The numbers at the given index.
   */
  java.lang.String getNumbers(int index);
  /**
   * <code>repeated string numbers = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the numbers at the given index.
   */
  com.google.protobuf.ByteString
      getNumbersBytes(int index);
}
