// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.asy.tests.grpc.proto.user;

/**
 * Protobuf type {@code com.asy.tests.grpc.proto.user.CreateUserRequest}
 */
public final class CreateUserRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.asy.tests.grpc.proto.user.CreateUserRequest)
    CreateUserRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateUserRequest.newBuilder() to construct.
  private CreateUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateUserRequest() {
    name_ = "";
    email_ = "";
    type_ = 0;
    numbers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateUserRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.asy.tests.grpc.proto.user.User.internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.asy.tests.grpc.proto.user.User.internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.asy.tests.grpc.proto.user.CreateUserRequest.class, com.asy.tests.grpc.proto.user.CreateUserRequest.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_ = 0;
  /**
   * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
   * @return The type.
   */
  @java.lang.Override public com.asy.tests.grpc.proto.user.UserType getType() {
    com.asy.tests.grpc.proto.user.UserType result = com.asy.tests.grpc.proto.user.UserType.forNumber(type_);
    return result == null ? com.asy.tests.grpc.proto.user.UserType.UNRECOGNIZED : result;
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp birthdate_;
  /**
   * <code>.google.protobuf.Timestamp birthdate = 5;</code>
   * @return Whether the birthdate field is set.
   */
  @java.lang.Override
  public boolean hasBirthdate() {
    return birthdate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp birthdate = 5;</code>
   * @return The birthdate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getBirthdate() {
    return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
  }
  /**
   * <code>.google.protobuf.Timestamp birthdate = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder() {
    return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
  }

  public static final int ACTIVE_FIELD_NUMBER = 6;
  private boolean active_ = false;
  /**
   * <code>bool active = 6;</code>
   * @return The active.
   */
  @java.lang.Override
  public boolean getActive() {
    return active_;
  }

  public static final int NUMBERS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList numbers_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string numbers = 7;</code>
   * @return A list containing the numbers.
   */
  public com.google.protobuf.ProtocolStringList
      getNumbersList() {
    return numbers_;
  }
  /**
   * <code>repeated string numbers = 7;</code>
   * @return The count of numbers.
   */
  public int getNumbersCount() {
    return numbers_.size();
  }
  /**
   * <code>repeated string numbers = 7;</code>
   * @param index The index of the element to return.
   * @return The numbers at the given index.
   */
  public java.lang.String getNumbers(int index) {
    return numbers_.get(index);
  }
  /**
   * <code>repeated string numbers = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the numbers at the given index.
   */
  public com.google.protobuf.ByteString
      getNumbersBytes(int index) {
    return numbers_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (type_ != com.asy.tests.grpc.proto.user.UserType.STANDARD.getNumber()) {
      output.writeEnum(4, type_);
    }
    if (birthdate_ != null) {
      output.writeMessage(5, getBirthdate());
    }
    if (active_ != false) {
      output.writeBool(6, active_);
    }
    for (int i = 0; i < numbers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, numbers_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (type_ != com.asy.tests.grpc.proto.user.UserType.STANDARD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (birthdate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBirthdate());
    }
    if (active_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, active_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < numbers_.size(); i++) {
        dataSize += computeStringSizeNoTag(numbers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNumbersList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.asy.tests.grpc.proto.user.CreateUserRequest)) {
      return super.equals(obj);
    }
    com.asy.tests.grpc.proto.user.CreateUserRequest other = (com.asy.tests.grpc.proto.user.CreateUserRequest) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (type_ != other.type_) return false;
    if (hasBirthdate() != other.hasBirthdate()) return false;
    if (hasBirthdate()) {
      if (!getBirthdate()
          .equals(other.getBirthdate())) return false;
    }
    if (getActive()
        != other.getActive()) return false;
    if (!getNumbersList()
        .equals(other.getNumbersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasBirthdate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
    }
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActive());
    if (getNumbersCount() > 0) {
      hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getNumbersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asy.tests.grpc.proto.user.CreateUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.asy.tests.grpc.proto.user.CreateUserRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.asy.tests.grpc.proto.user.CreateUserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.asy.tests.grpc.proto.user.CreateUserRequest)
      com.asy.tests.grpc.proto.user.CreateUserRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.asy.tests.grpc.proto.user.User.internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.asy.tests.grpc.proto.user.User.internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.asy.tests.grpc.proto.user.CreateUserRequest.class, com.asy.tests.grpc.proto.user.CreateUserRequest.Builder.class);
    }

    // Construct using com.asy.tests.grpc.proto.user.CreateUserRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      name_ = "";
      email_ = "";
      type_ = 0;
      birthdate_ = null;
      if (birthdateBuilder_ != null) {
        birthdateBuilder_.dispose();
        birthdateBuilder_ = null;
      }
      active_ = false;
      numbers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.asy.tests.grpc.proto.user.User.internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_descriptor;
    }

    @java.lang.Override
    public com.asy.tests.grpc.proto.user.CreateUserRequest getDefaultInstanceForType() {
      return com.asy.tests.grpc.proto.user.CreateUserRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.asy.tests.grpc.proto.user.CreateUserRequest build() {
      com.asy.tests.grpc.proto.user.CreateUserRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.asy.tests.grpc.proto.user.CreateUserRequest buildPartial() {
      com.asy.tests.grpc.proto.user.CreateUserRequest result = new com.asy.tests.grpc.proto.user.CreateUserRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.asy.tests.grpc.proto.user.CreateUserRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.birthdate_ = birthdateBuilder_ == null
            ? birthdate_
            : birthdateBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.active_ = active_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        numbers_.makeImmutable();
        result.numbers_ = numbers_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.asy.tests.grpc.proto.user.CreateUserRequest) {
        return mergeFrom((com.asy.tests.grpc.proto.user.CreateUserRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.asy.tests.grpc.proto.user.CreateUserRequest other) {
      if (other == com.asy.tests.grpc.proto.user.CreateUserRequest.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasBirthdate()) {
        mergeBirthdate(other.getBirthdate());
      }
      if (other.getActive() != false) {
        setActive(other.getActive());
      }
      if (!other.numbers_.isEmpty()) {
        if (numbers_.isEmpty()) {
          numbers_ = other.numbers_;
          bitField0_ |= 0x00000040;
        } else {
          ensureNumbersIsMutable();
          numbers_.addAll(other.numbers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getBirthdateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              active_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureNumbersIsMutable();
              numbers_.add(s);
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.asy.tests.grpc.proto.user.UserType getType() {
      com.asy.tests.grpc.proto.user.UserType result = com.asy.tests.grpc.proto.user.UserType.forNumber(type_);
      return result == null ? com.asy.tests.grpc.proto.user.UserType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.asy.tests.grpc.proto.user.UserType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.asy.tests.grpc.proto.user.UserType type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp birthdate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> birthdateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     * @return Whether the birthdate field is set.
     */
    public boolean hasBirthdate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     * @return The birthdate.
     */
    public com.google.protobuf.Timestamp getBirthdate() {
      if (birthdateBuilder_ == null) {
        return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
      } else {
        return birthdateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     */
    public Builder setBirthdate(com.google.protobuf.Timestamp value) {
      if (birthdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        birthdate_ = value;
      } else {
        birthdateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     */
    public Builder setBirthdate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (birthdateBuilder_ == null) {
        birthdate_ = builderForValue.build();
      } else {
        birthdateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     */
    public Builder mergeBirthdate(com.google.protobuf.Timestamp value) {
      if (birthdateBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          birthdate_ != null &&
          birthdate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getBirthdateBuilder().mergeFrom(value);
        } else {
          birthdate_ = value;
        }
      } else {
        birthdateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     */
    public Builder clearBirthdate() {
      bitField0_ = (bitField0_ & ~0x00000010);
      birthdate_ = null;
      if (birthdateBuilder_ != null) {
        birthdateBuilder_.dispose();
        birthdateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getBirthdateBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getBirthdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder() {
      if (birthdateBuilder_ != null) {
        return birthdateBuilder_.getMessageOrBuilder();
      } else {
        return birthdate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp birthdate = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getBirthdateFieldBuilder() {
      if (birthdateBuilder_ == null) {
        birthdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getBirthdate(),
                getParentForChildren(),
                isClean());
        birthdate_ = null;
      }
      return birthdateBuilder_;
    }

    private boolean active_ ;
    /**
     * <code>bool active = 6;</code>
     * @return The active.
     */
    @java.lang.Override
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>bool active = 6;</code>
     * @param value The active to set.
     * @return This builder for chaining.
     */
    public Builder setActive(boolean value) {

      active_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool active = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearActive() {
      bitField0_ = (bitField0_ & ~0x00000020);
      active_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList numbers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureNumbersIsMutable() {
      if (!numbers_.isModifiable()) {
        numbers_ = new com.google.protobuf.LazyStringArrayList(numbers_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @return A list containing the numbers.
     */
    public com.google.protobuf.ProtocolStringList
        getNumbersList() {
      numbers_.makeImmutable();
      return numbers_;
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @return The count of numbers.
     */
    public int getNumbersCount() {
      return numbers_.size();
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @param index The index of the element to return.
     * @return The numbers at the given index.
     */
    public java.lang.String getNumbers(int index) {
      return numbers_.get(index);
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the numbers at the given index.
     */
    public com.google.protobuf.ByteString
        getNumbersBytes(int index) {
      return numbers_.getByteString(index);
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @param index The index to set the value at.
     * @param value The numbers to set.
     * @return This builder for chaining.
     */
    public Builder setNumbers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNumbersIsMutable();
      numbers_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @param value The numbers to add.
     * @return This builder for chaining.
     */
    public Builder addNumbers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNumbersIsMutable();
      numbers_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @param values The numbers to add.
     * @return This builder for chaining.
     */
    public Builder addAllNumbers(
        java.lang.Iterable<java.lang.String> values) {
      ensureNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, numbers_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumbers() {
      numbers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string numbers = 7;</code>
     * @param value The bytes of the numbers to add.
     * @return This builder for chaining.
     */
    public Builder addNumbersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureNumbersIsMutable();
      numbers_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.asy.tests.grpc.proto.user.CreateUserRequest)
  }

  // @@protoc_insertion_point(class_scope:com.asy.tests.grpc.proto.user.CreateUserRequest)
  private static final com.asy.tests.grpc.proto.user.CreateUserRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.asy.tests.grpc.proto.user.CreateUserRequest();
  }

  public static com.asy.tests.grpc.proto.user.CreateUserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateUserRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateUserRequest>() {
    @java.lang.Override
    public CreateUserRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateUserRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateUserRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.asy.tests.grpc.proto.user.CreateUserRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

