// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.asy.tests.grpc.proto.user;

public interface UserListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asy.tests.grpc.proto.user.UserListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.asy.tests.grpc.proto.user.UserResponse users = 1;</code>
   */
  java.util.List<com.asy.tests.grpc.proto.user.UserResponse> 
      getUsersList();
  /**
   * <code>repeated .com.asy.tests.grpc.proto.user.UserResponse users = 1;</code>
   */
  com.asy.tests.grpc.proto.user.UserResponse getUsers(int index);
  /**
   * <code>repeated .com.asy.tests.grpc.proto.user.UserResponse users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .com.asy.tests.grpc.proto.user.UserResponse users = 1;</code>
   */
  java.util.List<? extends com.asy.tests.grpc.proto.user.UserResponseOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .com.asy.tests.grpc.proto.user.UserResponse users = 1;</code>
   */
  com.asy.tests.grpc.proto.user.UserResponseOrBuilder getUsersOrBuilder(
      int index);
}
