// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.asy.tests.grpc.proto.user;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asy_tests_grpc_proto_user_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asy_tests_grpc_proto_user_CreateUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\035com.asy.tests.grpc.proto.u" +
      "ser\032\037google/protobuf/timestamp.proto\"\303\001\n" +
      "\021CreateUserRequest\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002" +
      " \001(\t\022\r\n\005email\030\003 \001(\t\0225\n\004type\030\004 \001(\0162\'.com." +
      "asy.tests.grpc.proto.user.UserType\022-\n\tbi" +
      "rthdate\030\005 \001(\0132\032.google.protobuf.Timestam" +
      "p\022\016\n\006active\030\006 \001(\010\022\017\n\007numbers\030\007 \003(\t\"5\n\022Cr" +
      "eateUserResponse\022\016\n\006status\030\001 \001(\005\022\017\n\007mess" +
      "age\030\002 \001(\t*+\n\010UserType\022\014\n\010STANDARD\020\000\022\010\n\004P" +
      "AID\020\001\022\007\n\003VIP\020\0022\202\001\n\013UserService\022s\n\ncreate" +
      "User\0220.com.asy.tests.grpc.proto.user.Cre" +
      "ateUserRequest\0321.com.asy.tests.grpc.prot" +
      "o.user.CreateUserResponse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asy_tests_grpc_proto_user_CreateUserRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Type", "Birthdate", "Active", "Numbers", });
    internal_static_com_asy_tests_grpc_proto_user_CreateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_asy_tests_grpc_proto_user_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asy_tests_grpc_proto_user_CreateUserResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
