// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.asy.tests.grpc.proto.user;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asy.tests.grpc.proto.user.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool active = 2;</code>
   * @return The active.
   */
  boolean getActive();
}
